[theme]
primaryColor = "#D62839"
backgroundColor = "#F4F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172033"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
